# Generated by Django 2.2.28 on 2024-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.TextField(max_length=100)),
                ('date', models.TextField(max_length=50)),
            ],
        ),
    ]
